baseURL = "https://hugo.gartzea.com/"
languageCode = "es-ES"
title = "Andrew Gartzea"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Andrew Gartzea"
  description = "Bitácora de Andrew Gartzea"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "andrewgartzea@egmail.com"
  Instagram     = "@andrewgartzea"
  Tiktok        = "@andrewgartzea"
  Telegram      = "@gartzeasstuff"
  Mastodon      = "@andrewgartzea"
  Kofi          = "andrewgartzea"
  RSS           = "/articulos/index.xml"

## Main Menu
[[menu.main]]
  name = "Artículos"
  weight = 100
  identifier = "Artículos"
  url = "/articulos/"
[[menu.main]]
  name = "Proyectos"
  identifier = "Proyectos"
  weight = 200
  url = "/proyectos/"

